{% set name = "makepackage" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/makepackage-{{ version }}.tar.gz
  sha256: c965b36624d5fb5be7d7b990481260e51cf5965a6936c1e088a739b35ff54b7f

build:
  entry_points:
    - makepackage = makepackage.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - easycheck
    - python >=3.6

test:
  imports:
    - makepackage
  commands:
    - pip check
    - makepackage --help
  requires:
    - pip

about:
  home: https://github.com/nyggus/makepackage
  summary: Creating a structure of a simple Python package
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
