{% set name = "makepackage" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/makepackage-{{ version }}.tar.gz
  sha256: c9776e55cd06496df1ae214a3aad0abc8237135caaaf3ecf1635573a17caf8f9

build:
  entry_points:
    - makepackage = makepackage.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - setuptools >=61.0
  run:
    - easycheck
    - python >={{ python_min }}

test:
  imports:
    - makepackage
  commands:
    - pip check
    - makepackage --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nyggus/makepackage
  summary: Creating a structure of a simple Python package
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
