{% set name = "makepackage" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/makepackage-{{ version }}.tar.gz
  sha256: c0adc58ff721795638e7e6916de2dceac82b6987f19d8cb406a12f013120dd15

build:
  entry_points:
    - makepackage = makepackage.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
    - setuptools >=61.0
  run:
    - easycheck
    - python >=3.7
    
test:
  imports:
    - makepackage
  commands:
    - pip check
    - makepackage --help
  requires:
    - pip

about:
  home: https://github.com/nyggus/makepackage
  summary: Creating a structure of a simple Python package
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
