{% set name = "makepackage" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/makepackage-{{ version }}.tar.gz
  sha256: 6ff136e650b6c4c5d29932072e94a9f598cc90c96f277a1ed00913e6920555e7

build:
  entry_points:
    - makepackage = makepackage.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - easycheck
    - python >=3.6

test:
  imports:
    - makepackage
  commands:
    - pip check
    - makepackage --help
  requires:
    - pip

about:
  home: https://github.com/nyggus/makepackage
  summary: Creating a structure of a simple Python package
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
